version: "3.4"

services:
  ejscontactform:
    image: ejs-contact-form-view
    container_name: ejs-view
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./src/
          target: /usr/src/app/src
          action: sync+restart
        - path: ./Dockerfile
          action: rebuild

  db:
    image: mysql/mysql-server:8.0.28
    restart: always
    container_name: ejs-db
    # env_file:
    #   - path: ./.env
    #     required: true
    volumes:
      - ejs-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  ejs-volume:
