version: "3.4"

services:
  ejscontactform:
    image: ejscontactform
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./src/
          target: /usr/src/app/src
          action: sync+restart
        - path: ./docker-compose.yml
          action: rebuild
